version: '3'

services:
  drupal:
    image: drupal:latest
    ports:
      - 81:80
    volumes:
      - drupal:/var/www/html
    restart: always
  

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 82:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql

volumes:
  wordpress:
  drupal:
  db:


# volumes:
#   drupal_modules:
#   drupal_profiles:
#   drupal_themes:
#   drupal_sites:
#   db_data:
